#!/bin/bash
#
# Shell script to update all needed development tools
# Run as intended user
#

# replace w/Unix `diff` or something else if needed
diffProg='git diff --no-index'

$diffProg ../configs/.gitconfig              ~/.gitconfig
$diffProg ../configs/.bashrc                 ~/.bashrc
$diffProg ../configs/.bash_profile           ~/.bash_profile
$diffProg ../configs/.inputrc                ~/.inputrc
$diffProg ../configs/.vimrc                  ~/.vimrc
$diffProg ../configs/.vim/colors/monokai.vim ~/.vim/colors/monokai.vim
$diffProg ../configs/.tmux.conf              ~/.tmux.conf
$diffProg ../configs/.config/ranger/rc.conf  ~/.config/ranger/rc.conf
$diffProg ../configs/.config/ranger/scope.sh ~/.config/ranger/scope.sh
$diffProg ../configs/.ctags                  ~/.ctags
$diffProg ../configs/.glbl_gitignore         ~/.glbl_gitignore
