#!/usr/bin/env bash
#
# Shell script to install all needed development tools and software
# Run as intended user, should be somewhat platform agnostic
#

echo "Install started at $(date)"

# Make common src/ dir
mkdir -p ~/src/

# Note meslo S is a good macOS-like powerline font
pushd ~/src/
echo "Installing Powerline fonts"
git clone https://github.com/powerline/fonts.git
pushd fonts/
./install.sh
popd
popd

# Add `tmux` terminal types to support italic/bold in tmux
tic -x ../configs/tmux.terminfo

## Cron jobs
# check for brew package updates every hour
crontab '*/5 * * * * /usr/local/bin/brew update &> /dev/null && if [ -n "(/usr/local/bin/brew outdated)" ] ; then echo " ⚑ Brew Updates Available: $(/usr/local/bin/brew outdated | wc -l) " > /tmp/sys_package_updates; else echo "" > /tmp/sys_package_updates; fi'

echo "Current cron jobs:"
crontab -l

echo "Installing vim components..."

echo "Installing vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing vim-colorschemes"
git clone https://github.com/flazz/vim-colorschemes.git
mkdir -p ~/.vim/colors/
cp vim-colorschemes/colors/* ~/.vim/colors/
rm -rf vim-colorschemes/

echo "Installing dotfiles"
./update_configs

