#!/usr/bin/env bash
#
# Shell script to install all needed development tools and software
# Run as intended user, should be somewhat platform agnostic
#

echo "Install started at $(date)"

# Make common src/ dir
mkdir -p ~/src/

# install Ruby since most likely not pre-installed on *nix (except Fedora)
echo "Installing rbenv and ruby-build"
mkdir -p ~/.rbenv
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
pushd ~/.rbenv
src/configure
make -C src
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bash_profile
popd

echo "Installing Ruby 2.4.1"
rbenv install -v 2.4.1
rbenv global 2.4.1

## Install via pkg managers: https://github.com/powerline/fonts
#echo "Installing Powerline fonts"
#wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
#wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
## check this is valid path to fonts by `$ xset q`
#mv PowerlineSymbols.otf /usr/share/fonts/X11/misc/
## `$ fc-cache` may need sudo rights
#fc-cache -vf /usr/share/fonts/X11/misc/
#mkdir -p ~/.config/fontconfig/conf.d/
#mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/

# Add `tmux` terminal types to support italic/bold in tmux (may not be needed for Fedora)
tic -x ./configs/xterm-256color-italic.terminfo
tic -x ./configs/tmux-256color.terminfo

## Cron jobs
# check for brew package updates every hour
crontab '*/5 * * * * if [ $(/usr/bin/yum check-update | sed '1,/^$/d' | wc -l) -ge 1 ] ; then echo " ⚑ Yum Updates Available: $(/usr/bin/yum check-update | sed '1,/^$/d' | wc -l) " > /tmp/sys_package_updates; else echo "" > /tmp/sys_package_updates; fi'

echo "Current cron jobs:"
crontab -l

echo "Installing vim components..."

echo "Installing vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing vim-colorschemes"
git clone https://github.com/flazz/vim-colorschemes.git
mkdir -p ~/.vim/colors/
cp vim-colorschemes/colors/* ~/.vim/colors/
rm -rf vim-colorschemes/

echo "Installing dotfiles"
./update_configs

