#!/usr/bin/env bash
#
# Shell script to install all needed development tools and software
# Run as intended user, should be somewhat platform agnostic
#

echo "Install started at $(date)"

# Make common src/ dir
mkdir -p ~/src/

## Install via pkg managers: https://github.com/powerline/fonts
#echo "Installing Powerline fonts"
#wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
#wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
## check this is valid path to fonts by `$ xset q`
#mv PowerlineSymbols.otf /usr/share/fonts/X11/misc/
## `$ fc-cache` may need sudo rights
#fc-cache -vf /usr/share/fonts/X11/misc/
#mkdir -p ~/.config/fontconfig/conf.d/
#mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/

# Add `tmux` terminal types to support italic/bold in tmux (may not be needed for Fedora)
tic -x ./configs/xterm-256color-italic.terminfo
tic -x ./configs/tmux-256color.terminfo

## Cron jobs
# check for brew package updates every hour
crontab '*/5 * * * * if [ $(/usr/bin/yum check-update | sed '1,/^$/d' | wc -l) -ge 1 ] ; then echo " ⚑ Yum Updates Available: $(/usr/bin/yum check-update | sed '1,/^$/d' | wc -l) " > /tmp/sys_package_updates; else echo "" > /tmp/sys_package_updates; fi'

echo "Current cron jobs:"
crontab -l

# tmux 2.9a install from src
sudo yum remove -y tmux

msg "Installing tmux from source..."
pushd /tmp/ > /dev/null
msg "NOTE: Check for tmux release updates at https://github.com/tmux/tmux/releases"
wget https://github.com/tmux/tmux/releases/download/2.9a/tmux-2.9a.tar.gz
tar -xzf tmux-2.9a.tar.gz
pushd tmux-2.9a > /dev/null
./configure && make
sudo make install
popd > /dev/null
popd > /dev/null

# Vim install from src w/clipboard & python support
msg "Installing Vim from source..."
# NOTE: remove shipping Vim
  sudo yum remove -y vim-enhanced vim-common
  sudo yum-builddep vim

if [ -d "vim" ]; then
  pushd vim/ > /dev/null
  git pull
else
  git clone https://github.com/vim/vim.git
  pushd vim/ > /dev/null
fi

./configure --with-features=huge \
  --enable-multibyte \
  --enable-rubyinterp=yes \
  --enable-pythoninterp=yes \
  --enable-perlinterp=yes \
  --enable-gui=auto \
  --enable-gtk2-check \
  --with-x

# If installing for single user (no `make install`) VIMRUNTIMEDIR can == {vim_src}/runtime
make VIMRUNTIMEDIR=/usr/local/share/vim/vim80
# sometimes `sudo` is removed with vim
if ! command -v sudo > /dev/null; then
  su -c yum install -y sudo
fi

sudo make install
hash vim
popd > /dev/null

echo "Installing vim components..."

echo "Installing vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing vim-colorschemes"
git clone https://github.com/flazz/vim-colorschemes.git
mkdir -p ~/.vim/colors/
cp vim-colorschemes/colors/* ~/.vim/colors/
rm -rf vim-colorschemes/

echo "Installing dotfiles"
./update_configs

