#!/bin/bash
#
# Shell script to update all needed development tools
# Run as intended user
#

# First copy local files over if they're newer
cp  -u  ~/.gitconfig                               ../configs/.gitconfig
cp  -u  ~/.bashrc                                  ../configs/.bashrc
cp  -u  ~/.bash_profile                            ../configs/.bash_profile
cp  -u  ~/.inputrc                                 ../configs/.inputrc
cp  -u  ~/.vimrc                                   ../configs/.vimrc
cp  -u  ~/.vim/colors/monokai.vim                  ../configs/.vim/colors/monokai.vim
cp  -u  ~/.tmux.conf                               ../configs/.tmux.conf
cp  -u  ~/.config/ranger/rc.conf                   ../configs/.config/ranger/rc.conf
cp  -u  ~/.config/ranger/scope.sh                  ../configs/.config/ranger/scope.sh
cp  -u  ~/.ctags                                   ../configs/.ctags
cp  -u  ~/.glbl_gitignore                          ../configs/.glbl_gitignore
# Then copy remote files over if they're newer
cp  -u  ../configs/.gitconfig                      ~/.gitconfig
cp  -u  ../configs/.bashrc                         ~/.bashrc
cp  -u  ../configs/.bash_profile                   ~/.bash_profile
cp  -u  ../configs/.inputrc                        ~/.inputrc
cp  -u  ../configs/.vimrc                          ~/.vimrc
mkdir -p ~/.vim/colors/
cp  -u  ../configs/.vim/colors/monokai.vim         ~/.vim/colors/monokai.vim
cp  -u  ../configs/.tmux.conf                      ~/.tmux.conf
cp  -u  ../configs/.config/ranger/rc.conf          ~/.config/ranger/rc.conf
cp  -u  ../configs/.config/ranger/scope.sh         ~/.config/ranger/scope.sh
cp  -u  ../configs/.ctags                          ~/.ctags
cp  -u  ../configs/.glbl_gitignore                 ~/.glbl_gitignore
